name: ieee_discounts_application
description: "IEEE Computer Society  JU Discounts Application ( IEEE CS JU Card )"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  http: ^1.3.0
  auto_size_text: ^3.0.0
  loading_indicator: ^3.1.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  provider: ^6.1.4
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logos/
    - lib/assets/images/icons/

  fonts:
    - family: MontserratArabic
      fonts:
        - asset: lib/assets/fonts/Montserrat-Arabic Black 900.otf
          weight: 900
        - asset: lib/assets/fonts/Montserrat-Arabic ExtraBold 800.otf
          weight: 800
        - asset: lib/assets/fonts/Montserrat-Arabic Bold 700.otf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-Arabic SemiBold 600.otf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-Arabic Medium 500.otf
          weight: 500
        - asset: lib/assets/fonts/Montserrat-Arabic Regular 400.otf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-Arabic Light 300.otf
          weight: 300

flutter_launcher_icons:
  android: true # Generate icons for Android
  image_path: "lib/assets/images/logos/icon.png"
  adaptive_icon_background: "#F6F6F6" # Background color for adaptive icons
  adaptive_icon_foreground: "lib/assets/images/logos/icon.png" # Foreground image for adaptive icons
  adaptive_icon_foreground_inset: 22

flutter_native_splash:
  color: "#F6F6F6" # Background color
  image:  "lib/assets/images/logos/ieee cs logo black-splash.png"
  android: true
